

# This file was *autogenerated* from the file my_samples.sage
from sage.all_cmdline import *   # import sage library

load_attach_path('/mnt/c/Users/glisc/projects/DynaBase')
import sys
sys.path.append("/mnt/c/Users/glisc/projects/DynaBase")

# quadratic data
load("connect.py")
load("sample_data/add_quadratic_data.py")


